export const STOCK_CONST = {
  JQUANTS_STOCK_COLS: [
    {jp: '証券コード', en: 'Code', dataType: 'string', show: true},
    {jp: '日付', en: 'Date', dataType: 'string', show: true},
    {jp: '始値', en: 'Open', dataType: 'number', show: true},
    {jp: '高値', en: 'High', dataType: 'number', show: true},
    {jp: '安値', en: 'Low', dataType: 'number', show: true},
    {jp: '終値', en: 'Close', dataType: 'number', show: true},
    {jp: '出来高', en: 'Volume', dataType: 'number', show: true},
    {jp: '調整係数', en: 'AdjustmentFactor', dataType: 'number'},
    {jp: '調整始値', en: 'AdjustmentOpen', dataType: 'number'},
    {jp: '調整高値', en: 'AdjustmentHigh', dataType: 'number'},
    {jp: '調整安値', en: 'AdjustmentLow', dataType: 'number'},
    {jp: '調整終値', en: 'AdjustmentClose', dataType: 'number'},
    {jp: '調整出来高', en: 'AdjustmentVolume', dataType: 'number'},
  ],

  JQUANTS_STOCK_HISTORY_COLS: [
    {jp: '日付', en: 'Date', dataType: 'string', show: true}, // YYYY-MM-DD
    {jp: '証券コード', en: 'Code', dataType: 'string', show: true},
    {jp: '始値', en: 'Open', dataType: 'number', show: true},
    {jp: '高値', en: 'High', dataType: 'number', show: true},
    {jp: '安値', en: 'Low', dataType: 'number', show: true},
    {jp: '終値', en: 'Close', dataType: 'number', show: true},
    {jp: '出来高', en: 'Volume', dataType: 'number', show: true},
    {jp: '調整係数', en: 'AdjustmentFactor', dataType: 'number'},
    {jp: '調整始値', en: 'AdjustmentOpen', dataType: 'number'},
    {jp: '調整高値', en: 'AdjustmentHigh', dataType: 'number'},
    {jp: '調整安値', en: 'AdjustmentLow', dataType: 'number'},
    {jp: '調整終値', en: 'AdjustmentClose', dataType: 'number'},
    {jp: '調整出来高', en: 'AdjustmentVolume', dataType: 'number'},
  ],

  Y_FINANCE_COLS: [
    {jp: '略称', en: 'shortName', dataType: 'string', show: true},
    {jp: '証券コード', en: 'symbol', dataType: 'string', show: true},
    {jp: '始値', en: 'regularMarketOpen', dataType: 'number', show: true},
    {jp: '現在値', en: 'regularMarketPrice', dataType: 'number', show: true},
    {jp: '市場', en: 'market', dataType: 'string'},
    {jp: '市場状態', en: 'marketState', dataType: 'string'},
    {jp: '言語', en: 'language', dataType: 'string'},
    {jp: '地域', en: 'region', dataType: 'string'},
    {jp: '銘柄種別', en: 'quoteType', dataType: 'string'},
    {jp: '種別表示', en: 'typeDisp', dataType: 'string'},
    {jp: '株価情報ソース名', en: 'quoteSourceName', dataType: 'string'},
    {jp: 'トリガー可能', en: 'triggerable', dataType: 'boolean'},
    {jp: 'カスタム価格アラート信頼度', en: 'customPriceAlertConfidence', dataType: 'string'},
    {jp: '通貨', en: 'currency', dataType: 'string'},
    {jp: '会社名（正式名称）', en: 'longName', dataType: 'string'},
    {jp: '情報更新間隔（秒）', en: 'sourceInterval', dataType: 'number'},
    {jp: '取引所データ遅延（秒）', en: 'exchangeDataDelayedBy', dataType: 'number'},
    {jp: '取引可能', en: 'tradeable', dataType: 'boolean'},
    {jp: '仮想通貨取引可能', en: 'cryptoTradeable', dataType: 'boolean'},
    {jp: '前日比（価格変動）', en: 'regularMarketChange', dataType: 'number', show: true},
    {jp: '当日高値', en: 'regularMarketDayHigh', dataType: 'number'},
    {jp: '当日値幅', en: 'regularMarketDayRange', dataType: 'object', show: true},
    {jp: '当日安値', en: 'regularMarketDayLow', dataType: 'number', show: true},
    {jp: '出来高', en: 'regularMarketVolume', dataType: 'number', show: true},
    {jp: 'PER（直近1年）', en: 'trailingPE', dataType: 'number'},

    {jp: '前日終値', en: 'regularMarketPreviousClose', dataType: 'number'},
    {jp: '買気配値', en: 'bid', dataType: 'number'},
    {jp: '売気配値', en: 'ask', dataType: 'number'},
    {jp: '買気配数量', en: 'bidSize', dataType: 'number'},
    {jp: '売気配数量', en: 'askSize', dataType: 'number'},
    {jp: '取引所名', en: 'fullExchangeName', dataType: 'string'},

    {jp: '3ヶ月平均出来高', en: 'averageDailyVolume3Month', dataType: 'number'},
    {jp: '10日平均出来高', en: 'averageDailyVolume10Day', dataType: 'number'},
    {jp: '52週安値からの変化', en: 'fiftyTwoWeekLowChange', dataType: 'number'},
    {jp: '52週安値からの変化率', en: 'fiftyTwoWeekLowChangePercent', dataType: 'number'},
    {jp: '52週レンジ', en: 'fiftyTwoWeekRange', dataType: 'object'},
    {jp: '52週高値からの変化', en: 'fiftyTwoWeekHighChange', dataType: 'number'},
    {jp: '52週高値からの変化率', en: 'fiftyTwoWeekHighChangePercent', dataType: 'number'},
    {jp: '52週安値', en: 'fiftyTwoWeekLow', dataType: 'number'},
    {jp: '52週高値', en: 'fiftyTwoWeekHigh', dataType: 'number'},
    {jp: '52週変化率', en: 'fiftyTwoWeekChangePercent', dataType: 'number'},

    {jp: 'EPS（直近1年）', en: 'epsTrailingTwelveMonths', dataType: 'number'},
    {jp: '50日移動平均', en: 'fiftyDayAverage', dataType: 'number'},
    {jp: '50日移動平均からの変化', en: 'fiftyDayAverageChange', dataType: 'number'},
    {jp: '50日移動平均からの変化率', en: 'fiftyDayAverageChangePercent', dataType: 'number'},
    {jp: '200日移動平均', en: 'twoHundredDayAverage', dataType: 'number'},
    {jp: '200日移動平均からの変化', en: 'twoHundredDayAverageChange', dataType: 'number'},
    {jp: '200日移動平均からの変化率', en: 'twoHundredDayAverageChangePercent', dataType: 'number'},

    // 日本株特有
    {jp: '平均アナリスト評価', en: 'averageAnalystRating', dataType: 'string'},
    {jp: '財務通貨', en: 'financialCurrency', dataType: 'string'},
    {jp: '配当金（直近1年）', en: 'trailingAnnualDividendRate', dataType: 'number', show: true},
    {jp: '配当金', en: 'dividendRate', dataType: 'number'},
    {jp: '配当利回り（直近1年）', en: 'trailingAnnualDividendYield', dataType: 'number', show: true},
    {jp: '配当利回り', en: 'dividendYield', dataType: 'number'},
    {jp: '予想EPS', en: 'epsForward', dataType: 'number'},
    {jp: '発行済株式数', en: 'sharesOutstanding', dataType: 'number'},
    {jp: '1株あたり純資産', en: 'bookValue', dataType: 'number', show: true},
    {jp: '時価総額', en: 'marketCap', dataType: 'number'},
    {jp: '予想PER', en: 'forwardPE', dataType: 'number'},
    {jp: 'PBR', en: 'priceToBook', dataType: 'number'},
    {jp: '決算発表日時', en: 'earningsTimestamp', dataType: 'string'},
    {jp: '決算発表開始日時', en: 'earningsTimestampStart', dataType: 'string'},
    {jp: '決算発表終了日時', en: 'earningsTimestampEnd', dataType: 'string'},

    // ETF特有
    {jp: 'YTDリターン', en: 'ytdReturn', dataType: 'number'},
    {jp: '直近3ヶ月リターン', en: 'trailingThreeMonthReturns', dataType: 'number'},
    {jp: '直近3ヶ月NAVリターン', en: 'trailingThreeMonthNavReturns', dataType: 'number'},
    {jp: '純資産総額', en: 'netAssets', dataType: 'number'},
    {jp: '経費率', en: 'netExpenseRatio', dataType: 'number'},
    {jp: 'アフターマーケットｍ変化率', en: 'postMarketChangePercent', dataType: 'number'},
    {jp: 'アフターマーケット価格', en: 'postMarketPrice', dataType: 'number'},
    {jp: 'アフターマーケット変化', en: 'postMarketChange', dataType: 'number'},
    {jp: 'アフターマーケット時刻', en: 'postMarketTime', dataType: 'string'},
    {jp: '取引所', en: 'exchange', dataType: 'string'},
    {jp: 'メッセージボードID', en: 'messageBoardId', dataType: 'string'},
    {jp: '取引所タイムゾーン名', en: 'exchangeTimezoneName', dataType: 'string'},
    {jp: '取引所タイムゾーン略称', en: 'exchangeTimezoneShortName', dataType: 'string'},
    {jp: 'GMTオフセット（ミリ秒）', en: 'gmtOffSetMilliseconds', dataType: 'number'},
    {jp: 'ESG情報有無', en: 'esgPopulated', dataType: 'boolean'},
    {jp: 'プレ・ポストマーケットデータ有無', en: 'hasPrePostMarketData', dataType: 'boolean'},
    {jp: '初回取引日', en: 'firstTradeDateMilliseconds', dataType: 'string'},
    {jp: '価格表示単位', en: 'priceHint', dataType: 'number'},
  ],
}
